"""Analyst agent."""

import logging

from multi_agent_research_lab.agents.base import BaseAgent
from multi_agent_research_lab.core.schemas import AgentName, AgentResult
from multi_agent_research_lab.core.state import ResearchState
from multi_agent_research_lab.services.llm_client import LLMClient

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = """You are a senior research analyst.
Convert research notes into structured analysis.
Required sections:
1. Key findings
2. Evidence strength
3. Contradictions or uncertainty
4. Practical implications
5. Recommended answer angle
Be direct, evidence-aware, and do not add unsupported facts."""


class AnalystAgent(BaseAgent):
    """Turns research notes into structured insights."""

    name = "analyst"

    def __init__(self) -> None:
        self._llm = LLMClient(temperature=0.1)

    def run(self, state: ResearchState) -> ResearchState:
        """Populate `state.analysis_notes`.

        Existing research notes and sources are preserved.
        """

        try:
            source_summary = "\n".join(
                f"[{index}] {source.title}: {source.snippet[:250]}"
                for index, source in enumerate(state.sources, start=1)
            )
            user_prompt = (
                f"Original query:\n{state.request.query}\n\n"
                f"Research notes:\n{state.research_notes or '(missing)'}\n\n"
                f"Sources:\n{source_summary or '(none)'}\n\n"
                "Analyze the material for the writer."
            )
            response = self._llm.complete(_SYSTEM_PROMPT, user_prompt)
            content = response.content.strip()
            if response.error:
                state.errors.append(f"Analyst LLM fallback: {response.error}")
            if not content:
                content = (
                    "Analysis notes could not be generated by the LLM. "
                    "Use the research notes directly and treat evidence quality as unverified:\n"
                    f"{state.research_notes or state.request.query}"
                )
                state.errors.append("Analyst received an empty LLM response.")
            state.analysis_notes = content
            state.agent_results.append(
                AgentResult(
                    agent=AgentName.ANALYST,
                    content=content,
                    metadata={
                        "input_tokens": response.input_tokens,
                        "output_tokens": response.output_tokens,
                        "cost_usd": response.cost_usd,
                        "llm_error": response.error,
                    },
                )
            )
            state.add_trace_event("analyst", {"analysis_length": len(content)})
        except Exception as exc:
            logger.exception("Analyst failed")
            state.errors.append(f"Analyst failed safely: {exc}")
            state.analysis_notes = (
                "Analysis step failed. Limited notes available:\n"
                f"{state.research_notes or state.request.query}"
            )
            state.add_trace_event("analyst", {"error": str(exc)})

        return state
