"""Researcher agent."""

import logging

from multi_agent_research_lab.agents.base import BaseAgent
from multi_agent_research_lab.core.schemas import AgentName, AgentResult
from multi_agent_research_lab.core.state import ResearchState
from multi_agent_research_lab.services.llm_client import LLMClient
from multi_agent_research_lab.services.search_client import SearchClient

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = """You are a careful research agent.
Your job is to read search results and produce concise research notes.
Rules:
- Preserve source references as [1], [2], ...
- Separate confirmed facts from weak or missing evidence.
- Do not invent sources or facts that are not present in the provided context.
- Write in clear Markdown bullets."""


class ResearcherAgent(BaseAgent):
    """Collects sources and creates concise research notes."""

    name = "researcher"

    def __init__(self) -> None:
        self._llm = LLMClient(temperature=0.2)
        self._search = SearchClient()

    def run(self, state: ResearchState) -> ResearchState:
        """Populate `state.sources` and `state.research_notes`.

        Existing state is preserved; only sources, research_notes, trace, errors,
        and agent_results are updated.
        """

        try:
            sources = self._search.search(
                state.request.query,
                max_results=state.request.max_sources,
            )
            seen_sources = {(source.url, source.title) for source in state.sources}
            new_sources = [
                source for source in sources if (source.url, source.title) not in seen_sources
            ]
            state.sources.extend(new_sources)

            source_context = "\n".join(
                (
                    f"[{index}] {source.title}\n"
                    f"URL: {source.url or 'N/A'}\n"
                    f"Snippet: {source.snippet}"
                )
                for index, source in enumerate(sources, start=1)
            )
            if not source_context:
                source_context = "No source documents were returned."

            user_prompt = (
                f"Original research query:\n{state.request.query}\n\n"
                f"Search context:\n{source_context}\n\n"
                "Create research notes that the analyst can use next."
            )
            response = self._llm.complete(_SYSTEM_PROMPT, user_prompt)
            content = response.content.strip()
            if response.error:
                state.errors.append(f"Researcher LLM fallback: {response.error}")
            if not content:
                content = (
                    "Research notes could not be generated by the LLM. "
                    "Use the retrieved source snippets as the research context:\n"
                    f"{source_context}"
                )
                state.errors.append("Researcher received an empty LLM response.")
            state.research_notes = content
            state.agent_results.append(
                AgentResult(
                    agent=AgentName.RESEARCHER,
                    content=content,
                    metadata={
                        "sources_found": len(sources),
                        "input_tokens": response.input_tokens,
                        "output_tokens": response.output_tokens,
                        "cost_usd": response.cost_usd,
                        "llm_error": response.error,
                    },
                )
            )
            state.add_trace_event(
                "researcher",
                {"sources_found": len(sources), "notes_length": len(content)},
            )
        except Exception as exc:
            logger.exception("Researcher failed")
            state.errors.append(f"Researcher failed safely: {exc}")
            state.research_notes = (
                "Research step failed. Use the original query as limited context: "
                f"{state.request.query}"
            )
            state.add_trace_event("researcher", {"error": str(exc)})

        return state
