"""Writer agent."""

import logging

from multi_agent_research_lab.agents.base import BaseAgent
from multi_agent_research_lab.core.schemas import AgentName, AgentResult
from multi_agent_research_lab.core.state import ResearchState
from multi_agent_research_lab.services.llm_client import LLMClient

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT_TEMPLATE = """You are a technical writer.
Write the final answer for {audience}.
Rules:
- Use Markdown.
- Start with a direct answer.
- Use headings and bullets where useful.
- Include source references like [1], [2] when sources exist.
- Add a short "Sources" section at the end.
- Do not claim certainty when the evidence is weak."""


class WriterAgent(BaseAgent):
    """Produces final answer from research and analysis notes."""

    name = "writer"

    def __init__(self) -> None:
        self._llm = LLMClient(temperature=0.3)

    def run(self, state: ResearchState) -> ResearchState:
        """Populate `state.final_answer`.

        Existing research and analysis notes are preserved.
        """

        try:
            source_refs = "\n".join(
                f"[{index}] {source.title} - {source.url or 'N/A'}"
                for index, source in enumerate(state.sources, start=1)
            )
            user_prompt = (
                f"Original query:\n{state.request.query}\n\n"
                f"Research notes:\n{state.research_notes or '(missing)'}\n\n"
                f"Analysis notes:\n{state.analysis_notes or '(missing)'}\n\n"
                f"Sources:\n{source_refs or '(none)'}\n\n"
                "Write the final answer."
            )
            response = self._llm.complete(
                _SYSTEM_PROMPT_TEMPLATE.format(audience=state.request.audience),
                user_prompt,
            )
            content = response.content.strip()
            if response.error:
                state.errors.append(f"Writer LLM fallback: {response.error}")
            if not content:
                content = (
                    "# Final Answer\n\n"
                    "The LLM returned an empty response. Below is the best available "
                    "answer context from the analysis step.\n\n"
                    f"{state.analysis_notes or state.research_notes or state.request.query}"
                )
                state.errors.append("Writer received an empty LLM response.")
            state.final_answer = content
            state.agent_results.append(
                AgentResult(
                    agent=AgentName.WRITER,
                    content=content,
                    metadata={
                        "input_tokens": response.input_tokens,
                        "output_tokens": response.output_tokens,
                        "cost_usd": response.cost_usd,
                        "llm_error": response.error,
                    },
                )
            )
            state.add_trace_event("writer", {"answer_length": len(content)})
        except Exception as exc:
            logger.exception("Writer failed")
            state.errors.append(f"Writer failed safely: {exc}")
            state.final_answer = (
                "Final answer could not be generated by the LLM.\n\n"
                f"Query: {state.request.query}\n\n"
                f"Available analysis:\n{state.analysis_notes or state.research_notes or '(none)'}"
            )
            state.add_trace_event("writer", {"error": str(exc)})

        return state
